### ISSUE TITLE
cmake AVCODEC_INCLUDE_DIR error

### ISSUE THREAD

**Issue by rajb245** [osh/gr-mediatools#4]
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> AVCODEC_INCLUDE_DIR

It would be useful to have a readme with the details of how to set these variables correctly, if it's compatible with FFmpeg and/or the Libav forks, etc. I'm going to read the CMakeLists, but do you have any tips on what cmake flags to set, and what directories to point things to?

**Comment by osh** [comment]
you should not need to set any of these manually -- 
install libavcodec-dev and cmake should find them
ffmpeg is not required
perhaps an error message suggesting this if avcoded is not found would be useful --

**Comment by rajb245** [comment]
Just FYI both libavformat and libavcodec are required.

`sudo apt-get install libavcodec-dev libavformat-dev`
