### ISSUE TITLE
Build failed!

### ISSUE THREAD

**Issue by asim800** [osh/gr-mediatools#5]
Hi,

I have successfully installed gnuradio, gr-burst gr-pyqt and gr-pcap on **Ubuntu 16.10 (recently upgraded)** using **pybombs**. I am using **version 6 of gcc/g++** compilers.

> **sudo pybombs -v -p gr install gr-mediatools**

I get build failure with the following **error**:

PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j1'
[  5%] Building CXX object lib/CMakeFiles/gnuradio-mediatools.dir/mediatools_audiosource_impl.cc.o
/home/hercules/coding/gr/src/gr-mediatools/lib/mediatools_audiosource_impl.cc: In member function ‘void mediatools_audiosource_impl::readData(std::vector<short int>&)’:
/home/hercules/coding/gr/src/gr-mediatools/lib/mediatools_audiosource_impl.cc:91:39: error: ‘avcodec_alloc_frame’ was not declared in this scope
         d_frame = avcodec_alloc_frame();
                                       ^
lib/CMakeFiles/gnuradio-mediatools.dir/build.make:86: recipe for target 'lib/CMakeFiles/gnuradio-mediatools.dir/mediatools_audiosource_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-mediatools.dir/mediatools_audiosource_impl.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-mediatools.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-mediatools.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Thanks for your help.
Asim
---------------------------------------------------------------------------------------------------------------------------------
Here's a fuller log:
hercules@WH:~/coding/gnu/rml/dataset$ sudo pybombs -v -p gr install gr-mediatools
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /etc/pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {}
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /home/hercules/.pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {'default_prefix': '/home/hercules/coding/gr'}
PyBOMBS.ConfigManager - DEBUG - Template directory: /usr/local/lib/python2.7/dist-packages/pybombs/templates
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /etc/pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /home/hercules/.pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Resolving prefix alias gr.
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Choosing prefix dir from command line: /home/hercules/coding/gr
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Choosing default prefix config dir: /home/hercules/coding/gr/.pybombs
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /home/hercules/coding/gr/.pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix source dir is: /home/hercules/coding/gr/src
PyBOMBS.Inventory - DEBUG - Trying to load inventory file /home/hercules/coding/gr/.pybombs/inventory.yml...
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix-local recipe dir is: /home/hercules/coding/gr/.pybombs/recipes
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /home/hercules/coding/gr/.pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {}
PyBOMBS.ConfigManager - DEBUG - Full list of recipe locations: ['/home/hercules/coding/gr/.pybombs/recipes', '/home/hercules/coding/gr/.pybombs/recipes/gr-etcetera', '/home/hercules/coding/gr/.pybombs/recipes/gr-mapper', '/home/hercules/coding/gr/.pybombs/recipes/gr-recipes', '/home/hercules/.pybombs/recipes/gr-etcetera', '/home/hercules/.pybombs/recipes/gr-recipes', '/usr/local/lib/python2.7/dist-packages/pybombs/recipes']
PyBOMBS.ConfigManager - DEBUG - Named recipe locations: {'gr-mapper': 'https://github.com/gr-vt/gr-mapper.git', 'gr-etcetera': 'git+https://github.com/gnuradio/gr-etcetera.git', 'gr-recipes': 'git+https://github.com/gnuradio/gr-recipes.git'}
PyBOMBS - INFO - PyBOMBS Version 2.3.1a0
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/hercules/coding/gr/.pybombs/recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/hercules/coding/gr/.pybombs/recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 0 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/hercules/coding/gr/.pybombs/recipes/gr-etcetera
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/hercules/coding/gr/.pybombs/recipes/gr-etcetera' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 79 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/hercules/coding/gr/.pybombs/recipes/gr-mapper
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/hercules/coding/gr/.pybombs/recipes/gr-mapper' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 0 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/hercules/coding/gr/.pybombs/recipes/gr-recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/hercules/coding/gr/.pybombs/recipes/gr-recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 167 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/hercules/.pybombs/recipes/gr-etcetera
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/hercules/.pybombs/recipes/gr-etcetera' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 79 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/hercules/.pybombs/recipes/gr-recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/hercules/.pybombs/recipes/gr-recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 167 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /usr/local/lib/python2.7/dist-packages/pybombs/recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/usr/local/lib/python2.7/dist-packages/pybombs/recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 11 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.install - DEBUG - Initializing command class for command install
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt
PyBOMBS.PackageManager - DEBUG - apt is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager yumdnf
PyBOMBS.PackageManager - DEBUG - yumdnf is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager port
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager brew
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pacman
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager portage
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pymod
PyBOMBS.PackageManager - DEBUG - pymod is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using binary packagers: ['pip', 'apt', 'yumdnf', 'pymod', 'pkgconfig', 'cmd']
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.PackageManager - DEBUG - Checking if package gr-mediatools is installable...
PyBOMBS.PackageManager - DEBUG - Package gr-mediatools is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package gr-mediatools is installed...
PyBOMBS.PackageManager - DEBUG - Package gr-mediatools is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Package gr-mediatools is not installed.
PyBOMBS.install_manager - DEBUG - Testing binary install for package gr-mediatools.
PyBOMBS.PackageManager - DEBUG - install(gr-mediatools, install_type=binary, static=False)
PyBOMBS.PackageManager - DEBUG - Package gr-mediatools is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Returning no packagers -- package is requesting source build, but binary build is requested.
PyBOMBS.PackageManager - DEBUG - Checking if package gnuradio is installable...
PyBOMBS.PackageManager - DEBUG - Package gnuradio is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package gnuradio is installed...
PyBOMBS.PackageManager - DEBUG - Package gnuradio is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package libav is installable...
PyBOMBS.Packager.apt - DEBUG - Package libavcodec-dev has version 3.0.7 in repositories
PyBOMBS.Packager.apt - DEBUG - Package libavformat-dev has version 3.0.7 in repositories
PyBOMBS.Packager.apt - DEBUG - Package libavutil-dev has version 3.0.7 in repositories
PyBOMBS.PackageManager - DEBUG - Checking if package libav is installed...
PyBOMBS.Packager.apt - DEBUG - Package libavcodec-dev has version 3.0.7 installed
PyBOMBS.Packager.apt - DEBUG - Package libavformat-dev has version 3.0.7 installed
PyBOMBS.Packager.apt - DEBUG - Package libavutil-dev has version 3.0.7 installed
PyBOMBS.PackageManager - DEBUG - Checking if package cmake is installable...
PyBOMBS.PackageManager - DEBUG - Checking if package cmake is installed...
PyBOMBS.Packager.apt - DEBUG - Package cmake has version 3.5.2 installed
PyBOMBS.Packager.apt - DEBUG - Package cmake-data has version 3.5.2 installed
Install tree:
|
\- gr-mediatools
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: gr-mediatools
PyBOMBS.PackageManager - DEBUG - install(gr-mediatools, install_type=source, static=False)
PyBOMBS.PackageManager - DEBUG - Package gr-mediatools is requesting a source build.
PyBOMBS.PackageManager - DEBUG - Checking if package gr-mediatools is installed...
PyBOMBS.PackageManager - DEBUG - Package gr-mediatools is not installed.
PyBOMBS.PackageManager - DEBUG - Using packager source
PyBOMBS.Packager.source - DEBUG - State on package gr-mediatools is 0
PyBOMBS.Fetcher - DEBUG - Fetching source for recipe: gr-mediatools
PyBOMBS.Fetcher - DEBUG - Switching to src directory: /home/hercules/coding/gr/src
PyBOMBS.Fetcher - DEBUG - Getting fetcher for https://github.com/osh/gr-mediatools.git, type git
PyBOMBS.Fetcher - DEBUG - Using fetcher <pybombs.fetchers.git.Git object at 0x7f8e9bdd0990>
PyBOMBS.Fetcher.git - DEBUG - Requiring packages on host system: ['git']
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt
PyBOMBS.PackageManager - DEBUG - apt is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager yumdnf
PyBOMBS.PackageManager - DEBUG - yumdnf is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager port
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager brew
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pacman
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager portage
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pymod
PyBOMBS.PackageManager - DEBUG - pymod is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using binary packagers: ['pip', 'apt', 'yumdnf', 'pymod', 'pkgconfig', 'cmd']
PyBOMBS.install_manager - DEBUG - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.PackageManager - DEBUG - Checking if package git is installable...
PyBOMBS.PackageManager - DEBUG - Checking if package git is installed...
PyBOMBS.Packager.apt - DEBUG - Package git-core has version 2.9.3 installed
PyBOMBS.install_manager - DEBUG - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.Fetcher.git - DEBUG - Requirements met.
PyBOMBS.Fetcher.git - DEBUG - Using url - https://github.com/osh/gr-mediatools.git
PyBOMBS._process_thread() - DEBUG - Executing command `git clone https://github.com/osh/gr-mediatools.git gr-mediatools -b master'
Cloning:     (100%) [=====================================================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 0
PyBOMBS.Inventory - DEBUG - Setting state to `fetched'
PyBOMBS.Inventory - DEBUG - Saving inventory to file /home/hercules/coding/gr/.pybombs/inventory.yml...
PyBOMBS.Requirer - DEBUG - Requiring packages on host system: []
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt
PyBOMBS.PackageManager - DEBUG - apt is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager yumdnf
PyBOMBS.PackageManager - DEBUG - yumdnf is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager port
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager brew
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pacman
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager portage
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pymod
PyBOMBS.PackageManager - DEBUG - pymod is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using binary packagers: ['pip', 'apt', 'yumdnf', 'pymod', 'pkgconfig', 'cmd']
PyBOMBS.install_manager - DEBUG - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.PackageManager - DEBUG - Checking if package build-essential is installable...
PyBOMBS.Packager.apt - DEBUG - Package build-essential has version 12.1 in repositories
PyBOMBS.PackageManager - DEBUG - Checking if package build-essential is installed...
PyBOMBS.Packager.apt - DEBUG - Package build-essential has version 12.1 installed
PyBOMBS.install_manager - DEBUG - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.Requirer - DEBUG - Requirements met.
PyBOMBS.Packager.source - DEBUG - Using build directory: /home/hercules/coding/gr/src/gr-mediatools/build
PyBOMBS.Packager.source - DEBUG - Configuring recipe gr-mediatools
PyBOMBS.Packager.source - DEBUG - Using vars - {'config_opt': '', 'builddir': '/home/hercules/coding/gr/src/gr-mediatools/build'}
PyBOMBS.Packager.source - DEBUG - In cwd - /home/hercules/coding/gr/src/gr-mediatools/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/hercules/coding/gr  -Wno-dev'
Configuring: (100%) [=====================================================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 0
PyBOMBS.Packager.source - DEBUG - Configure successful.
PyBOMBS.Inventory - DEBUG - Setting state to `configured'
PyBOMBS.Inventory - DEBUG - Saving inventory to file /home/hercules/coding/gr/.pybombs/inventory.yml...
PyBOMBS.Packager.source - DEBUG - Building recipe gr-mediatools
PyBOMBS.Packager.source - DEBUG - In cwd - /home/hercules/coding/gr/src/gr-mediatools/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j4'
Building:    (100%) [=====================================================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - DEBUG - Building recipe gr-mediatools
PyBOMBS.Packager.source - DEBUG - In cwd - /home/hercules/coding/gr/src/gr-mediatools/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j1'
[  5%] Building CXX object lib/CMakeFiles/gnuradio-mediatools.dir/mediatools_audiosource_impl.cc.o
/home/hercules/coding/gr/src/gr-mediatools/lib/mediatools_audiosource_impl.cc: In member function ‘void mediatools_audiosource_impl::readData(std::vector<short int>&)’:
/home/hercules/coding/gr/src/gr-mediatools/lib/mediatools_audiosource_impl.cc:91:39: error: ‘avcodec_alloc_frame’ was not declared in this scope
         d_frame = avcodec_alloc_frame();
                                       ^
lib/CMakeFiles/gnuradio-mediatools.dir/build.make:86: recipe for target 'lib/CMakeFiles/gnuradio-mediatools.dir/mediatools_audiosource_impl.cc.o' failed
make[2]: *** [lib/CMakeFiles/gnuradio-mediatools.dir/mediatools_audiosource_impl.cc.o] Error 1
CMakeFiles/Makefile2:135: recipe for target 'lib/CMakeFiles/gnuradio-mediatools.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-mediatools.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gr-mediatools:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package gr-mediatools. Aborting.

**Comment by asim800** [comment]
I needed to change the offending line 
d_frame = avcodec_alloc_frame();
 in mediatools_audiosource_impl.cc with:
d_frame = av_frame_alloc();

I was able successfully install gr-mediatools after the change.

Thanks

**Comment by pachpandepriti** [comment]
Where do u make this  change?

**Comment by GalAvineri** [comment]
@asim800 Thank you! this worked!
@pachpandepriti the file is found in the path "<path>/lib/mediatools_audiosource_impl.cc"
where <path> is directory into which you downloaded this github repository.

**Comment by GalAvineri** [comment]
Although i am now stuck with the error "ImportError: No module named mediatools_swig"

**Comment by gongxiao-121** [comment]
> Although i am now stuck with the error "ImportError: No module named mediatools_swig"

I meet the same problem, do you solve this problem,please help me,thank U
