### ISSUE TITLE
how can I install this on windows?

### ISSUE THREAD

**Issue by hongdehua** [osh/gr-mediatools#8]
how can i install this lib on windows system? And how to use pybombs to install this lib?
Error during installing always occurs.

**Comment by lbb123** [comment]
能留个联系方式吗朋友？我也遇到这个问题了

**Comment by hongdehua** [comment]
你解决了这个问题吗？windows安装失败，最后在linux上安装了，windows上没解决。。。。

**Comment by hongdehua** [comment]
留个邮箱好了，hdehua@mail.ustc.edu.cn

**Comment by pachpandepriti** [comment]
HOw do I install this on ubuntu

**Comment by hongdehua** [comment]
Run the code,and according to the prompt install kinds of libraries( most of these are  gr-... )
I install pyCharm software firstly to operate code.

**Comment by hongdehua** [comment]
Detailed operation step by step I don't remember it now, because there are too many libraries

**Comment by pachpandepriti** [comment]
I am installing it on ubuntu 16.04. It would be great if you can recollect something or any other alternative so I can generate dataset

**Comment by hongdehua** [comment]
maybe you can refer to this blog.
https://blog.csdn.net/change_great/article/details/79052165

**Comment by lbb123** [comment]
hey,Can you leave your qq number ?

**Comment by pachpandepriti** [comment]
Thanks alot hongdehua.I will refer the link.
lbb123-What is qq number?

**Comment by hongdehua** [comment]
pachpandepriti - It's a social software account from China

**Comment by pachpandepriti** [comment]
hongdehua We have to connect one usrp while running this python file for generating dataset.Am I right? Can you leave your emailid please

**Comment by hongdehua** [comment]
@pachpandepriti  - we don't need usrp.
my email is as follow.
hdehua@mail.ustc.edu.cn
